### ISSUE TITLE
本地测试错误？

### ISSUE THREAD

**Issue by msojocs** [DavidNineRoc/qrcodeplus#11]
显示：
Fatal error: Uncaught Error: Class 'DavidNineRoc\Qrcode\Factory' not found in D:\wamp64\www\index.php on line 8
Error: Class 'DavidNineRoc\Qrcode\Factory' not found in D:\wamp64\www\index.php on line 8

请问时什么原因？

**Comment by seth-shi** [comment]
因为之前把用户名改了，导致 compsoer 用的是旧版本用户名无法自动加载，下载最新的就可以了
```
composer require davidnineroc/qrcodeplus dev-master
```
ps: 现在直接
```
composer require davidnineroc/qrcodeplus
```
就可以了，已经把旧版本删除了
